### ISSUE TITLE
relations

### ISSUE THREAD

**Issue by SampsonCrowley** [PhilWaldmann/openrecord#50]
There is no documentation on how to actually retrieve a relationship.

for instance:

```
module.exports = function (){
  this
  .validatesUniquenessOf('athlete_id')
  .validatesUniquenessOf('email')
  .validatesFormatOf('email', /^[^@\s\;]+@[^@\s\;]+\.[^@\s\;]+$/)
  .belongsTo('athlete')
  .hasMany('accountsUsers')
  .hasMany('users', {through: 'accountUsers'})
  .hasMany('infokits')
  .hasMany('account_audits')
}
```

how would I retrieve the 'users' for the above model?
how do I get the `athlete`?

**Comment by PhilWaldmann** [comment]
I'm currently working on getting the docs complete.

You could do the following:

```js
Model.join('athlete') //for a left join - or use .leftJoin(), rightJoin(), .innerJoin() or .outerJoin()
```
if you just want to prefetch relational data as well, use `.include()`.

The arguments for `.join()` and `.include()` could be a:
* `String` (relation name)
* `Array` with relation names
* `Object` where the key is the relation name. The value could by anything the `.include()` method accepts (`String`, `Array`, `Object`) - sub relations!

See [includes-test.js](https://github.com/PhilWaldmann/openrecord/blob/master/test/sql/__shared/includes-test.js#L367)

**Comment by SampsonCrowley** [comment]
so there's no method to fetch an association after the parent is loaded?

e.g. the example above model is 'Account' in the following example:

```
Account.get(MY_ID).exec().then((account) => account.athlete.load())
```

**Comment by PhilWaldmann** [comment]
With a `has_many` relation, you could do the following:
```js
Account.get(MY_ID).exec()
.then((account) => account.athletes.exec())
.then(athletes => console.log(athletes))
```
This currently only works with `has_many` and `belongsToMany`, because the relation object (empty array) has all conditions at hand. It's a preconfigured query like `Athlete.where({account_id: 1234})`. 
`belongs_to` relations return `null` for a record that isn't prefetched.

I've some ideas to solve this problem. But this is a breaking change, so another thing to address in `v2`
