### ISSUE TITLE
Model.create() with Array argument bug

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#83]
`Model.create([oneObject])` (array argument) is running beforeSave/beforeValidation twice
First time `record.isNewRecord` equals true. Second one `record.isNewRecord` equals false

**Comment by PhilWaldmann** [comment]
Thanks, I'll check that. Should call `beforeSave` hook only once.

**Comment by PhilWaldmann** [comment]
Postgres only: 
`beforeSave` was called once for the initial create (Multi insert) and a second time for an additional save. In order to mix new records with existing records, the second save call was added to make sure that everything got stored.
I've added additional code to ignore the second save for already inserted records.

Thanks

**Comment by PhilWaldmann** [comment]
Please check v.2.8.3
